# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b431382429e2a2ba557ef8b76a98480e432d7406b17638f222c7223368bdca71e655bb4d82ca5a5e3455b5d43b6183642a20371a6af2170e2f6fce52fa54157b

test:
  secret_key_base: d44ad9e41ac3fcb92e34db41a82e540719541bcb31d4bf919775bc89b5305d2cc413a543ab9c7d3257fec22ab88e6428ce86364586214bfbec56d8d2aed89ce9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
